### application.properties
#rocketmq.name-server=120.27.230.88:9876
#rocketmq.producer.group=my-group
## More relevant configurations for producing:
#rocketmq.producer.send-message-timeout=3000
#rocketmq.producer.compress-message-body-threshold=4096
#rocketmq.producer.max-message-size=4194304
#rocketmq.producer.retry-times-when-send-async-failed=0
#rocketmq.producer.retry-next-server=true
#rocketmq.producer.retry-times-when-send-failed=2
## 开启ACL
#rocketmq.producer.access-key=AK
#rocketmq.producer.secret-key=SK

rocketmq:
  name-server: 120.27.230.88:9876
  access-key: marketing-sales
  secret-key: 3daa3b8a-e2b9-4426-a855-281364879adf


# 动态配置  spring-config
#  server:
#    port: 8001
#
#  #指定注册中心地址
#  eureka:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:7001/eureka/
#
#  #服务的名称
#  spring:
#    application:
#      name: product-service
#    #指定从哪个配置中心读取
#    cloud:
#      config:
#        discovery:
#          service-id: config-server-jdbc
#          enabled: true
#        profile: dev
#        label: dev
